# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_totalFrame.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1120, 573)
        self.gridLayout_3 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_3.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 22)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navigator_label = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigator_label.sizePolicy().hasHeightForWidth())
        self.navigator_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.navigator_label.setFont(font)
        self.navigator_label.setAlignment(QtCore.Qt.AlignCenter)
        self.navigator_label.setObjectName("navigator_label")
        self.verticalLayout.addWidget(self.navigator_label)
        self.account_pushButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_pushButton.sizePolicy().hasHeightForWidth())
        self.account_pushButton.setSizePolicy(sizePolicy)
        self.account_pushButton.setObjectName("account_pushButton")
        self.verticalLayout.addWidget(self.account_pushButton)
        self.student_pushButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_pushButton.sizePolicy().hasHeightForWidth())
        self.student_pushButton.setSizePolicy(sizePolicy)
        self.student_pushButton.setObjectName("student_pushButton")
        self.verticalLayout.addWidget(self.student_pushButton)
        self.teacher_pushButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teacher_pushButton.sizePolicy().hasHeightForWidth())
        self.teacher_pushButton.setSizePolicy(sizePolicy)
        self.teacher_pushButton.setObjectName("teacher_pushButton")
        self.verticalLayout.addWidget(self.teacher_pushButton)
        self.module_pushButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_pushButton.sizePolicy().hasHeightForWidth())
        self.module_pushButton.setSizePolicy(sizePolicy)
        self.module_pushButton.setObjectName("module_pushButton")
        self.verticalLayout.addWidget(self.module_pushButton)
        self.attendance_pushButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attendance_pushButton.sizePolicy().hasHeightForWidth())
        self.attendance_pushButton.setSizePolicy(sizePolicy)
        self.attendance_pushButton.setObjectName("attendance_pushButton")
        self.verticalLayout.addWidget(self.attendance_pushButton)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_2.setHorizontalSpacing(7)
        self.gridLayout_2.setVerticalSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.page_5)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_13 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_13)
        self.comboBox_16 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_16)
        self.comboBox_14 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(30, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_10.addWidget(self.lineEdit_5)
        self.toolButton_20 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_20.setStyleSheet("border-image:url(:/all/images/searchIcon.png)")
        self.toolButton_20.setText("")
        self.toolButton_20.setObjectName("toolButton_20")
        self.horizontalLayout_10.addWidget(self.toolButton_20)
        self.horizontalLayout.addLayout(self.horizontalLayout_10)
        self.toolButton_21 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_21.setObjectName("toolButton_21")
        self.horizontalLayout.addWidget(self.toolButton_21)
        self.toolButton_22 = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_22.setObjectName("toolButton_22")
        self.horizontalLayout.addWidget(self.toolButton_22)
        self.toolButton_23 = QtWidgets.QToolButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_23.sizePolicy().hasHeightForWidth())
        self.toolButton_23.setSizePolicy(sizePolicy)
        self.toolButton_23.setMinimumSize(QtCore.QSize(30, 20))
        self.toolButton_23.setMaximumSize(QtCore.QSize(31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_23.setFont(font)
        self.toolButton_23.setObjectName("toolButton_23")
        self.horizontalLayout.addWidget(self.toolButton_23)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(self.frame_5)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 15)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_17 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_17)
        self.comboBox_18 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_18)
        self.comboBox_15 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(30, 30))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_11.addWidget(self.lineEdit_6)
        self.toolButton_24 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_24.setStyleSheet("border-image:url(:/all/images/searchIcon.png)")
        self.toolButton_24.setText("")
        self.toolButton_24.setObjectName("toolButton_24")
        self.horizontalLayout_11.addWidget(self.toolButton_24)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_11)
        self.toolButton_25 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_25.setObjectName("toolButton_25")
        self.horizontalLayout_2.addWidget(self.toolButton_25)
        self.toolButton_26 = QtWidgets.QToolButton(self.frame_6)
        self.toolButton_26.setObjectName("toolButton_26")
        self.horizontalLayout_2.addWidget(self.toolButton_26)
        self.toolButton_27 = QtWidgets.QToolButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_27.sizePolicy().hasHeightForWidth())
        self.toolButton_27.setSizePolicy(sizePolicy)
        self.toolButton_27.setMinimumSize(QtCore.QSize(30, 20))
        self.toolButton_27.setMaximumSize(QtCore.QSize(31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_27.setFont(font)
        self.toolButton_27.setObjectName("toolButton_27")
        self.horizontalLayout_2.addWidget(self.toolButton_27)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tableView_2 = QtWidgets.QTableView(self.frame_6)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_3.addWidget(self.tableView_2)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 15)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_20 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_20)
        self.comboBox_21 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_21)
        self.comboBox_19 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_19)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(30, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_12.addWidget(self.lineEdit_7)
        self.toolButton_28 = QtWidgets.QToolButton(self.frame_7)
        self.toolButton_28.setStyleSheet("border-image:url(:/all/images/searchIcon.png)")
        self.toolButton_28.setText("")
        self.toolButton_28.setObjectName("toolButton_28")
        self.horizontalLayout_12.addWidget(self.toolButton_28)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_12)
        self.toolButton_29 = QtWidgets.QToolButton(self.frame_7)
        self.toolButton_29.setObjectName("toolButton_29")
        self.horizontalLayout_3.addWidget(self.toolButton_29)
        self.toolButton_30 = QtWidgets.QToolButton(self.frame_7)
        self.toolButton_30.setObjectName("toolButton_30")
        self.horizontalLayout_3.addWidget(self.toolButton_30)
        self.toolButton_31 = QtWidgets.QToolButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_31.sizePolicy().hasHeightForWidth())
        self.toolButton_31.setSizePolicy(sizePolicy)
        self.toolButton_31.setMinimumSize(QtCore.QSize(30, 20))
        self.toolButton_31.setMaximumSize(QtCore.QSize(31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_31.setFont(font)
        self.toolButton_31.setObjectName("toolButton_31")
        self.horizontalLayout_3.addWidget(self.toolButton_31)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tableView_3 = QtWidgets.QTableView(self.frame_7)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_4.addWidget(self.tableView_3)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 15)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_8 = QtWidgets.QFrame(self.page_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_23 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_23)
        self.comboBox_24 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_24)
        self.comboBox_22 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_22)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(30, 30))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_13.addWidget(self.lineEdit_8)
        self.toolButton_32 = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_32.setStyleSheet("border-image:url(:/all/images/searchIcon.png)")
        self.toolButton_32.setText("")
        self.toolButton_32.setObjectName("toolButton_32")
        self.horizontalLayout_13.addWidget(self.toolButton_32)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_13)
        self.toolButton_33 = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_33.setObjectName("toolButton_33")
        self.horizontalLayout_4.addWidget(self.toolButton_33)
        self.toolButton_34 = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_34.setObjectName("toolButton_34")
        self.horizontalLayout_4.addWidget(self.toolButton_34)
        self.toolButton_35 = QtWidgets.QToolButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_35.sizePolicy().hasHeightForWidth())
        self.toolButton_35.setSizePolicy(sizePolicy)
        self.toolButton_35.setMinimumSize(QtCore.QSize(30, 20))
        self.toolButton_35.setMaximumSize(QtCore.QSize(31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_35.setFont(font)
        self.toolButton_35.setObjectName("toolButton_35")
        self.horizontalLayout_4.addWidget(self.toolButton_35)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tableView_4 = QtWidgets.QTableView(self.frame_8)
        self.tableView_4.setObjectName("tableView_4")
        self.verticalLayout_5.addWidget(self.tableView_4)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 15)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_9 = QtWidgets.QFrame(self.page_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_26 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_26)
        self.comboBox_27 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_27)
        self.comboBox = QtWidgets.QComboBox(self.frame_9)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_9)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_9)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_7.addWidget(self.dateEdit_2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(30, 30))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_15.addWidget(self.lineEdit_10)
        self.toolButton_40 = QtWidgets.QToolButton(self.frame_9)
        self.toolButton_40.setStyleSheet("border-image:url(:/all/images/searchIcon.png)")
        self.toolButton_40.setText("")
        self.toolButton_40.setObjectName("toolButton_40")
        self.horizontalLayout_15.addWidget(self.toolButton_40)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_15)
        self.toolButton_41 = QtWidgets.QToolButton(self.frame_9)
        self.toolButton_41.setObjectName("toolButton_41")
        self.horizontalLayout_8.addWidget(self.toolButton_41)
        self.toolButton_42 = QtWidgets.QToolButton(self.frame_9)
        self.toolButton_42.setObjectName("toolButton_42")
        self.horizontalLayout_8.addWidget(self.toolButton_42)
        self.toolButton_43 = QtWidgets.QToolButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_43.sizePolicy().hasHeightForWidth())
        self.toolButton_43.setSizePolicy(sizePolicy)
        self.toolButton_43.setMinimumSize(QtCore.QSize(30, 20))
        self.toolButton_43.setMaximumSize(QtCore.QSize(31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_43.setFont(font)
        self.toolButton_43.setObjectName("toolButton_43")
        self.horizontalLayout_8.addWidget(self.toolButton_43)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.tableView_5 = QtWidgets.QTableView(self.frame_9)
        self.tableView_5.setObjectName("tableView_5")
        self.verticalLayout_6.addWidget(self.tableView_5)
        self.verticalLayout_6.setStretch(0, 5)
        self.verticalLayout_6.setStretch(1, 2)
        self.verticalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.setStretch(3, 50)
        self.gridLayout_10.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 1, 1, 1)

        self.retranslateUi(Frame)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.navigator_label.setText(_translate("Frame", "Navigator"))
        self.account_pushButton.setText(_translate("Frame", "Account Management"))
        self.student_pushButton.setText(_translate("Frame", "Student Management"))
        self.teacher_pushButton.setText(_translate("Frame", "Teacher Management"))
        self.module_pushButton.setText(_translate("Frame", "Module Management"))
        self.attendance_pushButton.setText(_translate("Frame", "Attendance Management"))
        self.label.setText(_translate("Frame", "Account"))
        self.comboBox_13.setItemText(0, _translate("Frame", "UserType"))
        self.comboBox_16.setItemText(0, _translate("Frame", "Faculty"))
        self.comboBox_14.setItemText(0, _translate("Frame", "School"))
        self.toolButton_21.setText(_translate("Frame", "M"))
        self.toolButton_22.setText(_translate("Frame", "-"))
        self.toolButton_23.setText(_translate("Frame", "+"))
        self.label_2.setText(_translate("Frame", "Student"))
        self.comboBox_17.setItemText(0, _translate("Frame", "Faculty"))
        self.comboBox_18.setItemText(0, _translate("Frame", "School"))
        self.comboBox_15.setItemText(0, _translate("Frame", "Year"))
        self.toolButton_25.setText(_translate("Frame", "M"))
        self.toolButton_26.setText(_translate("Frame", "-"))
        self.toolButton_27.setText(_translate("Frame", "+"))
        self.label_3.setText(_translate("Frame", "Teacher"))
        self.comboBox_20.setItemText(0, _translate("Frame", "Faculty"))
        self.comboBox_21.setItemText(0, _translate("Frame", "School"))
        self.comboBox_19.setItemText(0, _translate("Frame", "Type"))
        self.toolButton_29.setText(_translate("Frame", "M"))
        self.toolButton_30.setText(_translate("Frame", "-"))
        self.toolButton_31.setText(_translate("Frame", "+"))
        self.label_4.setText(_translate("Frame", "Module"))
        self.comboBox_23.setItemText(0, _translate("Frame", "Faculty"))
        self.comboBox_24.setItemText(0, _translate("Frame", "School"))
        self.comboBox_22.setItemText(0, _translate("Frame", "Year"))
        self.toolButton_33.setText(_translate("Frame", "M"))
        self.toolButton_34.setText(_translate("Frame", "-"))
        self.toolButton_35.setText(_translate("Frame", "+"))
        self.label_5.setText(_translate("Frame", "Attendance"))
        self.comboBox_26.setItemText(0, _translate("Frame", "Faculty"))
        self.comboBox_27.setItemText(0, _translate("Frame", "School"))
        self.comboBox.setItemText(0, _translate("Frame", "Year"))
        self.comboBox_2.setItemText(0, _translate("Frame", "Course"))
        self.comboBox_3.setItemText(0, _translate("Frame", "SessionType"))
        self.label_6.setText(_translate("Frame", "Start Time:"))
        self.label_7.setText(_translate("Frame", "End Time:"))
        self.toolButton_41.setText(_translate("Frame", "M"))
        self.toolButton_42.setText(_translate("Frame", "-"))
        self.toolButton_43.setText(_translate("Frame", "+"))
import resources.images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Frame()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
