# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basicStructure_frame1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(730, 571)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setContentsMargins(30, 30, 30, 30)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.printTButton_TBS = QtWidgets.QToolButton(Frame)
        self.printTButton_TBS.setStyleSheet("border-image:url(:/all/images/printIcon.png)")
        self.printTButton_TBS.setText("")
        self.printTButton_TBS.setObjectName("printTButton_TBS")
        self.horizontalLayout.addWidget(self.printTButton_TBS)
        self.frameName_TBS = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameName_TBS.sizePolicy().hasHeightForWidth())
        self.frameName_TBS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.frameName_TBS.setFont(font)
        self.frameName_TBS.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frameName_TBS.setObjectName("frameName_TBS")
        self.horizontalLayout.addWidget(self.frameName_TBS)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, 25)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(30, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.search_horizontalLayout = QtWidgets.QHBoxLayout()
        self.search_horizontalLayout.setObjectName("search_horizontalLayout")
        self.search_lineEdit = QtWidgets.QLineEdit(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_lineEdit.sizePolicy().hasHeightForWidth())
        self.search_lineEdit.setSizePolicy(sizePolicy)
        self.search_lineEdit.setMinimumSize(QtCore.QSize(30, 30))
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.search_horizontalLayout.addWidget(self.search_lineEdit)
        self.search_toolButton = QtWidgets.QToolButton(Frame)
        self.search_toolButton.setStyleSheet("border-image:url(:/all/images/searchIcon.png)")
        self.search_toolButton.setText("")
        self.search_toolButton.setObjectName("search_toolButton")
        self.search_horizontalLayout.addWidget(self.search_toolButton)
        self.horizontalLayout_3.addLayout(self.search_horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(218, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.addButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.addButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listView = QtWidgets.QListView(Frame)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.PageNumlineEdit = QtWidgets.QLineEdit(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PageNumlineEdit.sizePolicy().hasHeightForWidth())
        self.PageNumlineEdit.setSizePolicy(sizePolicy)
        self.PageNumlineEdit.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PageNumlineEdit.setFont(font)
        self.PageNumlineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.PageNumlineEdit.setObjectName("PageNumlineEdit")
        self.horizontalLayout_6.addWidget(self.PageNumlineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leftPageButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftPageButton.sizePolicy().hasHeightForWidth())
        self.leftPageButton.setSizePolicy(sizePolicy)
        self.leftPageButton.setMaximumSize(QtCore.QSize(35, 35))
        self.leftPageButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.leftPageButton.setObjectName("leftPageButton")
        self.horizontalLayout_5.addWidget(self.leftPageButton)
        self.rightPageButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightPageButton.sizePolicy().hasHeightForWidth())
        self.rightPageButton.setSizePolicy(sizePolicy)
        self.rightPageButton.setMaximumSize(QtCore.QSize(35, 35))
        self.rightPageButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.rightPageButton.setObjectName("rightPageButton")
        self.horizontalLayout_5.addWidget(self.rightPageButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        self.printTButton_TBS.clicked.connect(self.print)
        self.PageNumlineEdit.returnPressed.connect(self.showNum)
        self.leftPageButton.clicked.connect(self.leftPage)
        self.rightPageButton.clicked.connect(self.rightPage)
        self.comboBox.currentTextChanged['QString'].connect(self.sort)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.frameName_TBS.setText(_translate("Frame", "FrameName"))
        self.comboBox.setItemText(0, _translate("Frame", "Sort"))
        self.comboBox.setItemText(1, _translate("Frame", "All"))
        self.comboBox.setItemText(2, _translate("Frame", "In Progress"))
        self.comboBox.setItemText(3, _translate("Frame", "Future"))
        self.comboBox.setItemText(4, _translate("Frame", "Past"))
        self.comboBox.setItemText(5, _translate("Frame", "Starred"))
        self.addButton.setText(_translate("Frame", "Add"))
        self.label_7.setText(_translate("Frame", "Show"))
        self.PageNumlineEdit.setText(_translate("Frame", "5"))
        self.leftPageButton.setText(_translate("Frame", "<"))
        self.rightPageButton.setText(_translate("Frame", ">"))
import resources.images_rc
